name: simple_storyboard
description: Faster iterative development of Flutter user interfaces by isolating widgets from your app. (Original Author is Mike Hoolehan <mike@hoolehan.com>, i just fork it and changes some things)
version: 0.0.4+1
author: Andrew Ananta <kuro.ketanitem@gmail.com>
homepage: https://github.com/anztrax/storyboard

dependencies:
  flutter:
    sdk: flutter
  recase: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
